name: Deploy new stand

on:
  workflow_dispatch:
    inputs:
      customer:
        description: customer-name
        required: true

env:
  ARGOCD_SERVER: argocd.dev.hydrosphere.io
  ARGOCD_VERSION: 2.1.2


jobs:
  prepare:
    name: Create ArgoCD application
    runs-on: ubuntu-latest
    
    steps:
      - name: Install ArgoCD CLI
        id: install_argocd
        shell: bash
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/${{ env.ARGOCD_VERSION }}/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
      
      - name: Check projects
        id: list_projects
        shell: bash
        run: |
          argocd proj list --server ${{ env.ARGOCD_SERVER }} --grpc-web --auth-token=${{ secrets.ARGOCD_TOKEN }} | grep ${{ github.event.inputs.customer }}


    
  
    