name: Deploy new stand

on:
  workflow_dispatch:
    inputs:
      customer:
        description: customer-name
        required: true

env:
  ARGOCD_SERVER: argocd.dev.hydrosphere.io


jobs:
  prepare:
    name: Create ArgoCD application
    runs-on: ubuntu-latest
    
    steps:
      - name: Install ArgoCD CLI
        id: install_argocd
        uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.1.2
          command: version
          options: --client
      
      - name: Check projects
        id: list_projects
        uses: clowdhaus/argo-cd-action/@main
        with: 
          version: 2.1.2
          command: proj list
          options: --server ${env.SERVER} --grpc-web --auth-token=${secrets.ARGOCD_TOKEN}

      - name: check output
        shell: bash
        run: echo ${{ steps.list_projects.outputs.output }}

    
  
    